# Generated by Django 5.1.3 on 2024-11-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('fundacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('combustible', models.CharField(max_length=50)),
                ('categorias', models.ManyToManyField(related_name='coches', to='appOutletDjango.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='appOutletDjango.marca')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='appOutletDjango.coche')),
            ],
        ),
    ]
