# Generated by Django 5.1.3 on 2024-11-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='categorias',
        ),
        migrations.AddField(
            model_name='coche',
            name='categoria',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='appOutletDjango.categoria'),
        ),
    ]
