# Generated by Django 5.1.3 on 2024-12-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletDjango', '0004_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='appOutletDjango.ofertacoche'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
